# Generated by Django 2.1.4 on 2018-12-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsliked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postsliked',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='PostsLiked',
        ),
    ]
